trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: ${{ values.dockerImage }}

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: pip install flask
  displayName: 'Install dependencies'

- script: docker build -t $(IMAGE_NAME):$(Build.BuildId) .
  displayName: 'Docker build'

- script: echo $(DOCKER_PASSWORD) | docker login $(IMAGE_NAME) -u $(DOCKER_USERNAME) --password-stdin
  displayName: 'Docker login'

- script: docker push $(IMAGE_NAME):$(Build.BuildId)
  displayName: 'Docker push'

- task: Kubernetes@1
  inputs:
    connectionType: 'KubeConfig'
    kubeconfig: '$(KUBECONFIG)'
    command: 'apply'
    arguments: '-f k8s/deployment.yaml -f k8s/service.yaml'
    namespace: 'default'
~                        
